version: '3.8'

services:
  web:
    build: ./project
    # dockerfile: ./project/Dockerfile.prod
    # dockerfile: ./project/Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8004
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8004
    environment:
      - ENVIRONMENT=dev
      - TESTING=1
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test
    depends_on: 
      - web-db

  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 5050:80  # You can change the host port as needed
    environment:
      PGADMIN_DEFAULT_EMAIL: ptermwendia@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - web-db